# Copyright (c) 2025 Michael Matta
# Homepage: https://github.com/Michael-Matta1/zsh-edit-select
#
# Pre-built binary downloader
#
# Provides two functions sourced lazily by plugin.zsh and loader-build.wsl.zsh
# only when a binary is absent.  On every other shell start the caller's
# [[ ! -x "$binary" ]] guard is false, this file is never sourced, and
# startup overhead is zero.
#
# Public API (both functions are defined at file scope once sourced):
#
#   _zes_fetch_binary <asset_name> <dest_path>
#       Downloads <asset_name> from the latest release to <dest_path>.
#       Verifies SHA256 before installing.  Returns 0 on success, 1 on any
#       failure — the caller is expected to fall back to `make`.
#
#   _zes_asset_name <impl> <binary_basename>
#       Prints the release asset filename for the current machine's arch.

# Guard: if already sourced in this session (e.g. both wayland and wsl paths
# are taken in the same shell), skip re-defining the functions.
(( ${+functions[_zes_fetch_binary]} )) && return 0

# ---------------------------------------------------------------------------
# _zes_fetch_binary <asset_name> <dest_path>
#
# Download, verify, and install a single release binary.
#
# The binary is written to a temp file first so that a failed or interrupted
# download never leaves a corrupt file at <dest_path>.  The temp file is
# removed on every error path.
#
# Returns 0 only when the binary is present, verified, and executable.
# Returns 1 on any failure without printing a message — the caller prints
# the final diagnostic once it knows whether the make fallback also failed.
# ---------------------------------------------------------------------------
function _zes_fetch_binary() {
  local _asset="$1"   # release asset filename, e.g. "zes-wl-selection-agent-aarch64"
  local _dest="$2"    # absolute path where the binary should land

  local _base_url="https://github.com/Michael-Matta1/zsh-edit-select/releases/latest/download"
  local _tmp="${_dest}.tmp.$$"
  local _dl_cmd=""

  # Resolve download command once.  Prefer curl; fall back to wget.
  # If neither is present there is nothing we can do — return immediately
  # so the caller falls back to `make` without printing a misleading message.
  if (( ${+commands[curl]} )); then
    _dl_cmd="curl -fsSL --retry 2 --connect-timeout 10 -o"
  elif (( ${+commands[wget]} )); then
    _dl_cmd="wget -q --tries=2 --timeout=10 -O"
  else
    return 1
  fi

  # Fail fast if the destination directory is not writable — no point in
  # making a network round-trip we cannot finish.
  [[ -w "${_dest:h}" ]] || return 1

  # ── Download ────────────────────────────────────────────────────────────
  eval "${_dl_cmd} ${(q)_tmp} ${(q)_base_url}/${_asset}" 2>/dev/null \
    || { rm -f "$_tmp"; return 1; }

  # Guard against an empty body returned with a successful HTTP status
  # (e.g. a CDN redirect that did not follow through correctly).
  [[ -s "$_tmp" ]] || { rm -f "$_tmp"; return 1; }

  # ── SHA256 verification ─────────────────────────────────────────────────
  # Fetch the sums file fresh each time.  We only reach this branch when a
  # binary is absent, so it is infrequent.  SHA256SUMS.txt is ~400 bytes.
  #
  # The checksum file generated by the release workflow contains entries with
  # directory prefixes, e.g.:
  #   a3f1...  linux-x86_64/zes-wl-selection-agent
  # The awk pattern matches the basename at the end of field 2 so this works
  # regardless of whether a prefix is present or absent.
  local _sums_tmp="${_dest:h}/.zes-SHA256SUMS.$$.tmp"

  if eval "${_dl_cmd} ${(q)_sums_tmp} ${(q)_base_url}/SHA256SUMS.txt" 2>/dev/null \
       && [[ -s "$_sums_tmp" ]]; then

    local _expected
    _expected=$(awk -v a="$_asset" \
      'NF==2 && ($2==a || substr($2,index($2,"/")+1)==a) { print $1; exit }' \
      "$_sums_tmp" 2>/dev/null)
    rm -f "$_sums_tmp"

    if [[ -n "$_expected" ]]; then
      local _actual=""
      if (( ${+commands[sha256sum]} )); then
        # Linux (coreutils)
        _actual=$(sha256sum "$_tmp" 2>/dev/null | awk '{print $1}')
      elif (( ${+commands[shasum]} )); then
        # macOS ships shasum, not sha256sum
        _actual=$(shasum -a 256 "$_tmp" 2>/dev/null | awk '{print $1}')
      fi
      # If no sha tool is available, _actual stays empty and we soft-pass.
      # This is unlikely in practice (both tools ship with every OS we target).
      if [[ -n "$_actual" && "$_actual" != "$_expected" ]]; then
        print -u2 "zsh-edit-select: checksum mismatch for ${_asset} — discarding"
        rm -f "$_tmp"
        return 1
      fi
    fi
    # No entry for this asset in the sums file (shouldn't happen with a
    # well-formed release, but be permissive rather than blocking install).

  else
    # Could not fetch the sums file — network issue, rate limit, etc.
    # Proceed without verification.  The make fallback is always available
    # for users who need a fully verified build.
    rm -f "$_sums_tmp"
  fi

  # ── Install ─────────────────────────────────────────────────────────────
  # Atomic rename: the binary becomes visible at its final path only after
  # the move succeeds, so it is never observable in a partial state.
  mv "$_tmp" "$_dest" && chmod +x "$_dest" \
    || { rm -f "$_tmp"; return 1; }

  return 0
}

# ---------------------------------------------------------------------------
# _zes_asset_name <impl> <binary_basename>
#
# Print the release asset filename for the current machine's OS and arch.
#
#   Linux x86_64   → <basename>           (default build, no suffix)
#   Linux aarch64  → <basename>-aarch64
#   macOS any      → <basename>           (universal fat binary, one file)
#   *.exe          → <basename>           (WSL helper is always x86_64)
#
# New architectures can be added to the case statement as CI jobs are added
# to release.yml.
# ---------------------------------------------------------------------------
function _zes_asset_name() {
  local _impl="$1"
  local _base="$2"

  # Windows PE cross-compiled for x86_64 — no arch suffix, always the same file.
  [[ "$_base" == *.exe ]] && { print "$_base"; return 0; }

  # macOS: the release ships one universal (fat) binary that covers both
  # Intel (x86_64) and Apple Silicon (arm64).  No suffix needed.
  [[ "$_impl" == "macos" ]] && { print "$_base"; return 0; }

  # Linux: select by uname -m.  Only x86_64 and aarch64/arm64 have prebuilt
  # binaries.  Any other arch returns 1 immediately so the caller skips the
  # download and falls straight through to the `make` source-build fallback.
  # This prevents silently downloading an x86_64 binary onto a RISC-V or
  # armv7l machine where it would fail at exec time with no useful message.
  local _arch
  _arch=$(uname -m 2>/dev/null)
  case "$_arch" in
    aarch64|arm64) print "${_base}-aarch64" ;;
    x86_64|amd64)  print "$_base" ;;
    *)
      print -u2 "zsh-edit-select: no prebuilt binary for arch '${_arch}' — will compile from source"
      return 1
      ;;
  esac

  return 0
}
